version: "3.8"

services:
  db:
    image: postgres:15
    container_name: learning_platform_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: learning_platform
    ports:
      #5433 la cong ben ngoai (hosting, may that) : 5432 la cong trong container
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: learning_platform_api
    restart: always
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      # loaicsdl://username:password@host:port/database_name
      DATABASE_URL: postgresql://postgres:admin@db:5432/learning_platform
      JWT_SECRET: 12736571242634823984126348239841
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && node dist/app.js"

volumes:
  pgdata:
